version: '3.9'
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - csv-data:/data/csv
      - ./init.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=POSTGRES_DB
volumes:
  csv-data:
