CREATE TABLE "outfield_players_current" (
	"UniqueID"	INTEGER,
	"first_name"	TEXT,
	"second_name"	TEXT,
	"Club"	TEXT,
	"Country"	TEXT,
	"Age"	INTEGER,
	"position_natural"	TEXT,
	"position_accomplished"	TEXT,
	"Foot"	TEXT,
	"Height"	INTEGER,
	"Weight"	INTEGER,
	"int_caps"	INTEGER,
	"int_goals"	INTEGER,
	"sell_value"	TEXT,
	"Wages"	TEXT,
	"contract_end"	TEXT,
	"Overall"	INTEGER,
	"Potential"	INTEGER,
	"image_url"	TEXT,
	"club_url"	TEXT,
	"country_url"	TEXT,
	"corners"	INTEGER,
	"crossing"	INTEGER,
	"dribbling"	INTEGER,
	"finishing"	INTEGER,
	"first-touch"	INTEGER,
	"free-kick-taking"	INTEGER,
	"heading"	INTEGER,
	"long-shots"	INTEGER,
	"long-throws"	INTEGER,
	"marking"	INTEGER,
	"passing"	INTEGER,
	"penalty-taking"	INTEGER,
	"tackling"	INTEGER,
	"technique"	INTEGER,
	"aggression"	INTEGER,
	"anticipation"	INTEGER,
	"bravery"	INTEGER,
	"composure"	INTEGER,
	"concentration"	INTEGER,
	"decisions"	INTEGER,
	"determination"	INTEGER,
	"flair"	INTEGER,
	"leadership"	INTEGER,
	"off-the-ball"	INTEGER,
	"positioning"	INTEGER,
	"teamwork"	INTEGER,
	"vision"	INTEGER,
	"work-rate"	INTEGER,
	"acceleration"	INTEGER,
	"agility"	INTEGER,
	"balance"	INTEGER,
	"jumping-reach"	INTEGER,
	"natural-fitness"	INTEGER,
	"pace"	INTEGER,
	"stamina"	INTEGER,
	"strength"	INTEGER
    , club_abbrev varchar(255),
      starting_position varchar(255)
);

--COPY "outfield_players_current"
--FROM '/data/csv/outfield.csv'
--DELIMITER ','
--CSV HEADER;
COPY "outfield_players_current" (
    "UniqueID",
    "first_name",
    "second_name",
    "Club",
    "Country",
    "Age",
    "position_natural",
    "position_accomplished",
    "Foot",
    "Height",
    "Weight",
    "int_caps",
    "int_goals",
    "sell_value",
    "Wages",
    "contract_end",
    "Overall",
    "Potential",
    "image_url",
    "club_url",
    "country_url",
    "corners",
    "crossing",
    "dribbling",
    "finishing",
    "first-touch",
    "free-kick-taking",
    "heading",
    "long-shots",
    "long-throws",
    "marking",
    "passing",
    "penalty-taking",
    "tackling",
    "technique",
    "aggression",
    "anticipation",
    "bravery",
    "composure",
    "concentration",
    "decisions",
    "determination",
    "flair",
    "leadership",
    "off-the-ball",
    "positioning",
    "teamwork",
    "vision",
    "work-rate",
    "acceleration",
    "agility",
    "balance",
    "jumping-reach",
    "natural-fitness",
    "pace",
    "stamina",
    "strength"
)
FROM '/data/csv/outfield.csv'
DELIMITER ','
CSV HEADER;

CREATE TABLE "goalkeepers_current" (
	"UniqueID"	INTEGER,
	"first_name"	TEXT,
	"second_name"	TEXT,
	"Club"	TEXT,
	"Country"	TEXT,
	"Age"	INTEGER,
	"position_natural"	TEXT,
	"position_accomplished"	TEXT,
	"Foot"	TEXT,
	"Height"	INTEGER,
	"Weight"	INTEGER,
	"int_caps"	INTEGER,
	"int_goals"	INTEGER,
	"sell_value"	TEXT,
	"Wages"	TEXT,
	"contract_end"	TEXT,
	"Overall"	INTEGER,
	"Potential"	INTEGER,
	"image_url"	TEXT,
	"club_url"	TEXT,
	"country_url"	TEXT,
	"aerial-reach"	INTEGER,
	"command-of-area"	INTEGER,
	"communication"	INTEGER,
	"eccentricity"	INTEGER,
	"first-touch"	INTEGER,
	"handling"	INTEGER,
	"kicking"	INTEGER,
	"one-on-ones"	INTEGER,
	"passing"	INTEGER,
	"punching-tendency"	INTEGER,
	"reflexes"	INTEGER,
	"rushing-out-tendency"	INTEGER,
	"throwing"	INTEGER,
	"aggression"	INTEGER,
	"anticipation"	INTEGER,
	"bravery"	INTEGER,
	"composure"	INTEGER,
	"concentration"	INTEGER,
	"decisions"	INTEGER,
	"determination"	INTEGER,
	"flair"	INTEGER,
	"leadership"	INTEGER,
	"off-the-ball"	INTEGER,
	"positioning"	INTEGER,
	"teamwork"	INTEGER,
	"vision"	INTEGER,
	"work-rate"	INTEGER,
	"acceleration"	INTEGER,
	"agility"	INTEGER,
	"balance"	INTEGER,
	"jumping-reach"	INTEGER,
	"natural-fitness"	INTEGER,
	"pace"	INTEGER,
	"stamina"	INTEGER,
	"strength"	INTEGER,
	"free-kick-taking"	INTEGER,
	"penalty-taking"	INTEGER,
	"technique"	INTEGER
, club_abbrev varchar(255), starting_position varchar(255)
);

