CREATE TABLE "outfield_players_current" (
    "uniqueid" INTEGER,
    "first_name" TEXT,
    "second_name" TEXT,
    "club" TEXT,
    "country" TEXT,
    "age" INTEGER,
    "position_natural" TEXT,
    "position_accomplished" TEXT,
    "foot" TEXT,
    "height" INTEGER,
    "weight" INTEGER,
    "int_caps" INTEGER,
    "int_goals" INTEGER,
    "sell_value" TEXT,
    "wages" TEXT,
    "contract_end" TEXT,
    "overall" INTEGER,
    "potential" INTEGER,
    "image_url" TEXT,
    "club_url" TEXT,
    "country_url" TEXT,
    "corners" INTEGER,
    "crossing" INTEGER,
    "dribbling" INTEGER,
    "finishing" INTEGER,
    "first_touch" INTEGER,
    "free_kick_taking" INTEGER,
    "heading" INTEGER,
    "long_shots" INTEGER,
    "long_throws" INTEGER,
    "marking" INTEGER,
    "passing" INTEGER,
    "penalty_taking" INTEGER,
    "tackling" INTEGER,
    "technique" INTEGER,
    "aggression" INTEGER,
    "anticipation" INTEGER,
    "bravery" INTEGER,
    "composure" INTEGER,
    "concentration" INTEGER,
    "decisions" INTEGER,
    "determination" INTEGER,
    "flair" INTEGER,
    "leadership" INTEGER,
    "off_the_ball" INTEGER,
    "positioning" INTEGER,
    "teamwork" INTEGER,
    "vision" INTEGER,
    "work_rate" INTEGER,
    "acceleration" INTEGER,
    "agility" INTEGER,
    "balance" INTEGER,
    "jumping_reach" INTEGER,
    "natural_fitness" INTEGER,
    "pace" INTEGER,
    "stamina" INTEGER,
    "strength" INTEGER,
    "club_abbrev" varchar(255),
    "starting_position" varchar(255)
);

COPY "outfield_players_current" (
    "uniqueid",
    "first_name",
    "second_name",
    "club",
    "country",
    "age",
    "position_natural",
    "position_accomplished",
    "foot",
    "height",
    "weight",
    "int_caps",
    "int_goals",
    "sell_value",
    "wages",
    "contract_end",
    "overall",
    "potential",
    "image_url",
    "club_url",
    "country_url",
    "corners",
    "crossing",
    "dribbling",
    "finishing",
    "first_touch",
    "free_kick_taking",
    "heading",
    "long_shots",
    "long_throws",
    "marking",
    "passing",
    "penalty_taking",
    "tackling",
    "technique",
    "aggression",
    "anticipation",
    "bravery",
    "composure",
    "concentration",
    "decisions",
    "determination",
    "flair",
    "leadership",
    "off_the_ball",
    "positioning",
    "teamwork",
    "vision",
    "work_rate",
    "acceleration",
    "agility",
    "balance",
    "jumping_reach",
    "natural_fitness",
    "pace",
    "stamina",
    "strength"
)
FROM '/data/csv/outfield.csv'
DELIMITER ','
CSV HEADER;

CREATE TABLE "goalkeepers_current" (
    "uniqueid" INTEGER,
    "first_name" TEXT,
    "second_name" TEXT,
    "club" TEXT,
    "country" TEXT,
    "age" INTEGER,
    "position_natural" TEXT,
    "position_accomplished" TEXT,
    "foot" TEXT,
    "height" INTEGER,
    "weight" INTEGER,
    "int_caps" INTEGER,
    "int_goals" INTEGER,
    "sell_value" TEXT,
    "wages" TEXT,
    "contract_end" TEXT,
    "overall" INTEGER,
    "potential" INTEGER,
    "image_url" TEXT,
    "club_url" TEXT,
    "country_url" TEXT,
    "aerial_reach" INTEGER,
    "command_of_area" INTEGER,
    "communication" INTEGER,
    "eccentricity" INTEGER,
    "first_touch" INTEGER,
    "handling" INTEGER,
    "kicking" INTEGER,
    "one_on_ones" INTEGER,
    "passing" INTEGER,
    "punching_tendency" INTEGER,
    "reflexes" INTEGER,
    "rushing_out_tendency" INTEGER,
    "throwing" INTEGER,
    "aggression" INTEGER,
    "anticipation" INTEGER,
    "bravery" INTEGER,
    "composure" INTEGER,
    "concentration" INTEGER,
    "decisions" INTEGER,
    "determination" INTEGER,
    "flair" INTEGER,
    "leadership" INTEGER,
    "off_the_ball" INTEGER,
    "positioning" INTEGER,
    "teamwork" INTEGER,
    "vision" INTEGER,
    "work_rate" INTEGER,
    "acceleration" INTEGER,
    "agility" INTEGER,
    "balance" INTEGER,
    "jumping_reach" INTEGER,
    "natural_fitness" INTEGER,
    "pace" INTEGER,
    "stamina" INTEGER,
    "strength" INTEGER,
    "free_kick_taking" INTEGER,
    "penalty_taking" INTEGER,
    "technique" INTEGER,
    "club_abbrev" varchar(255),
    "starting_position" varchar(255)
);

COPY "goalkeepers_current" (
    "uniqueid",
    "first_name",
    "second_name",
    "club",
    "country",
    "age",
    "position_natural",
    "position_accomplished",
    "foot",
    "height",
    "weight",
    "int_caps",
    "int_goals",
    "sell_value",
    "wages",
    "contract_end",
    "overall",
    "potential",
    "image_url",
    "club_url",
    "country_url",
    "aerial_reach",
    "command_of_area",
    "communication",
    "eccentricity",
    "first_touch",
    "handling",
    "kicking",
    "one_on_ones",
    "passing",
    "punching_tendency",
    "reflexes",
    "rushing_out_tendency",
    "throwing",
    "aggression",
    "anticipation",
    "bravery",
    "composure",
    "concentration",
    "decisions",
    "determination",
    "flair",
    "leadership",
    "off_the_ball",
    "positioning",
    "teamwork",
    "vision",
    "work_rate",
    "acceleration",
    "agility",
    "balance",
    "jumping_reach",
    "natural_fitness",
    "pace",
    "stamina",
    "strength",
    "free_kick_taking",
    "penalty_taking",
    "technique"
)
FROM '/data/csv/goalkeeper.csv'
DELIMITER ','
CSV HEADER;

CREATE TABLE "results" (
    "match_id" serial PRIMARY KEY,
    "home_team_name" TEXT,
    "home_score" INTEGER,
    "away_team_name" TEXT,
    "away_score" INTEGER,
    "date" DATE
);

CREATE TABLE "fixtures"(
    "match_id" serial PRIMARY KEY,
    "home_team_name" TEXT,
    "away_team_name" TEXT,
    "date" DATE
);