spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/POSTGRES_DB
      driverClassName: org.postgresql.Driver
      hikari.maximumPoolSize: 2
      username: user
      password: password
    jpa:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        show-sql: true
