spring:
    datasource:
      url: jdbc:sqlite:data/EdWoodwardDb.db
      driverClassName: org.sqlite.JDBC
      hikari.maximumPoolSize: 2
    jpa:
      database-platform: org.hibernate.community.dialect.SQLiteDialect
      hibernate:
        ddl-auto: update
        show-sql: true
        dialect: org.hibernate.community.dialect.SQLiteDialect
